variable "instance_type" {}
variable "access_key" {}
variable "secret_key" {}
variable "ami" {}
variable "subnet_id" {}
variable "key_name" {}
variable "vpc_security_group_ids" {}
variable "instance_name" {}
variable "associate_public_ip_address" {}
